### DISCUSSION TITLE
[suggestion] Github actions - install Chalet

### DISCUSSION THREAD

**Discussion by dimitre** [chalet-org/chalet#401] [General]
it would be great to have a github action that install Chalet in a runner [windows, macos, linux]
in the likes of ccache action: https://github.com/hendrikmuhs/ccache-action

It would be useful for this project where I intend to deploy libraries for OF (alternative to OF apothecary)
https://github.com/dimitre/ofChalet/

**Comment by dimitre** [comment]
I've made a step towards this, here is my test action working on three platforms
```yml
name: Chalet Multiplatform

on: [push, pull_request]

jobs:
  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Chalet
      uses: jaxxstorm/action-install-gh-release@v1.13.0
      with: 
        repo: chalet-org/chalet
        cache: enable
        extension: "\\.zip"
        prerelease: "true"

    - name: Get Path
      run: |
        echo $GITHUB_PATH

    - name: Chalet Test / Version
      run: |
        chalet --version


```
