### ISSUE TITLE
Meson build targets

### ISSUE THREAD

**Issue by dimitre** [chalet-org/chalet#384]
I'm trying to build this library with chalet
https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/INSTALL?ref_type=heads

**Comment by rewrking** [comment]
Yeah, that's a good idea. It would be a `mesonProject` target though, much like cmake ones. 

I do not want to add multi-line scripts. I think that's too complicated, when you can just check a script file into source control.

**Comment by dimitre** [comment]
I'm now trying to use scripts or process to make some operations, but I loose the variables magic.
if Chalet supported multiline bash like github actions it would be like this:
```yml
  freeimage_adjust:
    kind: shell
    shell: bash
    run: |
      mkdir ${external:FreeImage}/Source/include
      cp ${external:FreeImage}/Source/FreeImage.h ${external:FreeImage}/Source/include
```

If I do the same via scripts, I don't have a easy way to forward variables to the script, unless I specify multiple parameters. 
If I use process it gets tricky with PWD issues.
example
```yml
  PWD:
    kind: process
    path: pwd

  LIST:
    kind: process
    path: ls
    arguments:
      - ./${external:FreeImage}/Source/*.h
```

result:
```
▼  Process: PWD
/bin/pwd
/Users/d/src/ofLibs/freeimage
   PWD: 1ms

▼  Process: LIST
/bin/ls ./chalet_external/FreeImage/Source/*.h
ls: ./chalet_external/FreeImage/Source/*.h: No such file or directory
/bin/ls exited with code: 1
Error: Operation not permitted
✘  Failed!
   Review the errors above.

```
The file is present if I do the same in terminal.
