### ISSUE TITLE
bad formed yaml tabulation causing chalet to hang indefinetly

### ISSUE THREAD

**Issue by dimitre** [chalet-org/chalet#385]
First: Thanks for Yaml, I've just converted everything from json because the format doesn't accept commented out lines.

I found out some malformed yaml, mixing spaces and tabs was causing chalet to hang without an error message.
ZED editor with yaml validator pointed out the issue on Yaml file

**Comment by dimitre** [comment]
it can be any yml if you substitute two spaces by one tab

```yaml
name: libsof
version: "0.1.3"
externalDependencies:
  freetype:
    repository: https://gitlab.freedesktop.org/freetype/freetype
    tag: VER-2-13-3
    kind: git
targets:
  freetype:
    kind: cmakeProject
    location: ${external:${name}}
    recheck: false
    rebuild: false
    defines:
      - BUILD_SHARED_LIBS=OFF
      - CMAKE_BUILD_TYPE=Release
	- CMAKE_POSITION_INDEPENDENT_CODE=ON

      # - CMAKE_INCLUDE_OUTPUT_DIRECTORY=include
      # - CMAKE_INSTALL_INCLUDEDIR=include
    defines[platform:macos]:
      - CMAKE_OSX_DEPLOYMENT_TARGET=10.9
      - CMAKE_OSX_ARCHITECTURES=x86_64;arm64

distribution:
  freetype:
    kind: archive
    # condition: "[:macos]"
    format: zip
    include:
      - ${externalBuild:${name}}**.a
      - ${external:${name}}/include

```

**Comment by rewrking** [comment]
It doesn't hang for me, it just has a misleading error:

```
>  Reading Build File [chalet.yaml] ... 
ERROR: Failed to validate the file: chalet.yaml
ERROR: The object '(root)' contains an unknown property 'defines[platform:macos]': Not allowed.
```

I think the parser just skips over the line with the tab character, but it should explicitly call that out.

**Comment by dimitre** [comment]
I'll try to reproduce again and report back (or close this one)

**Comment by rewrking** [comment]
Even if you can't repro it, Let's keep it open. I do want to try to improve the errors.

**Comment by rewrking** [comment]
I found the infinite loop. It happens when object arrays aren't indented once:

(loops)

```yaml
testing:
- array: test
```

(works)
```yaml
testing:
  - array: test
```

**Comment by rewrking** [comment]
Okay, this has been fixed. You can try it out in the version below:

https://github.com/chalet-org/chalet/releases/tag/snapshot-main-202412210242

**Comment by dimitre** [comment]
Great! I'm testing with latest on github actions, will test this soon
in the meantime, another silent condition here:
I probably tried to do something unimplemented, in distribution I've tried to use this line:
```yml
include[:!windows]:
```
but I suppose this is only allowed in "condition" now.

```yaml
name: libsof
version: "0.1.3"
externalDependencies:
  freetype:
    repository: https://gitlab.freedesktop.org/freetype/freetype
    tag: VER-2-13-3
    kind: git
targets:
  freetype:
    kind: cmakeProject
    location: ${external:${name}}
    recheck: false
    rebuild: false
    defines:
      - BUILD_SHARED_LIBS=OFF
      - CMAKE_BUILD_TYPE=Release
      # - CMAKE_BUILD_TYPE=Release
      - CMAKE_POSITION_INDEPENDENT_CODE=ON
      # - CMAKE_INCLUDE_OUTPUT_DIRECTORY=include
      # - CMAKE_INSTALL_INCLUDEDIR=include
    defines[platform:macos]:
      - CMAKE_OSX_DEPLOYMENT_TARGET=10.9
      - CMAKE_OSX_ARCHITECTURES=x86_64;arm64

distribution:
  freetype:
    kind: archive
    # condition: "[:macos]"
    format: zip
    include:
      - ${external:${name}}/include
    # include[:macos]:
    #   - ${externalBuild:${name}}**.a
    # include[:web]:
    #   - ${externalBuild:${name}}**.a
    # include[:linux]:
    #   - ${externalBuild:${name}}**.a
    include[:windows]:
      - ${externalBuild:${name}}**.lib
      - ${externalBuild:${name}}**.pc
    include[:!windows]: #macos emscripten linux rpi
    - ${externalBuild:${name}}**.a
    # - ${externalBuild:${name}}*.a

```
